apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: kdt23/app:v1
        ports:
        - containerPort: 8082
